增加了一个系统是否交换过左右键的判断
ArtrixTech/BoomMine pull request #2
Opened 2018-05-18 02:42 UTC by chenfw2017

github小白第一次 pull request,大侠见凉：）
增加了一个系统是否交换过左右键的判断，可以方便少数左撇子，比如说我自己- -。

2018-05-22 13:02 UTC, ArtrixTech requested changes
注释的英文语法尽量还是正确哈~我当初的确没有考虑到左撇子的问题，您的pr在修改注释之后我会通过。
参考：# Check if the Mouse Primary Key had been changed

2018-06-04 07:33 UTC, merged

2018-06-04 07:33 UTC, ArtrixTech commented
Great

2018-06-04 07:34 UTC, chenfw2017 commented
英语不好，惭愧啊- -

2018-06-04 07:35 UTC, ArtrixTech commented
没事没事 试着慢慢要求自己用标准的语法来写注释 对工作或者和别人共享代码都有帮助的

2018-06-04 07:38 UTC, chenfw2017 commented
恩，谢谢大侠。